// AgriVault Data Fallback Provider for Serverless Deployments (Vercel)

export const MOCK_DEMO_BATCH_125 = {
  id: 'ON-2026-00125',
  batchCode: 'ON-2026-00125',
  crop: 'ONION',
  variety: 'Nashik Red Globe',
  source: 'Lasalgaon APMC Mandi',
  origin: 'Farm Cluster 4, Lasalgaon',
  weight: 500,
  quantityKg: 500,
  procurementDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  estimatedUnitValue: 100,
  totalBatchValue: 50000,
  sourceLocation: 'Farm Cluster 4, Lasalgaon',
  procurementLocation: 'Lasalgaon APMC Mandi, Nashik',
  registrationDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  status: 'IN_STORAGE',
  initialGrade: 'B',
  currentGrade: 'B',
  initialQualityScore: 78.0,
  qualityScore: 78.0,
  currentRiskScore: 78.0,
  riskScore: 78.0,
  currentRiskLevel: 'HIGH',
  potentialValueAtRisk: 12000,
  organizationId: 'org-demo-01',
  organization: {
    id: 'org-demo-01',
    name: 'AgriVault Post-Harvest Ops',
    code: 'AGRI-HQ-01',
  },
  samples: [
    {
      id: 'sample-125',
      batchId: 'ON-2026-00125',
      sampleSize: 100,
      sampledTop: true,
      sampledMiddle: true,
      sampledLeftSide: true,
      sampledRightSide: true,
      sampledLower: true,
      samplingNotes: 'Representative 100-onion sample drawn from 5 distinct cart depth quadrants.',
      timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
  inspections: [
    {
      id: 'insp-125',
      batchId: 'ON-2026-00125',
      inspectionType: 'INITIAL',
      status: 'COMPLETED',
      totalDetected: 100,
      acceptableCount: 76,
      lowerGradeCount: 17,
      rejectCount: 7,
      qualityScore: 78.0,
      grade: 'B',
      rescanDeltaCount: 0,
      inspectorName: 'Rajesh Sharma (Lead Inspector)',
      aiMode: 'DEMO_AI_MODE',
      createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
      timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
      images: [
        {
          id: 'img-125-1',
          inspectionId: 'insp-125',
          imageUrl: '/demo-onion-sample.jpg',
          imageType: 'PRIMARY',
          timestamp: new Date().toISOString(),
        },
      ],
      detections: Array.from({ length: 100 }).map((_, idx) => {
        const i = idx + 1;
        const rejectIndices = new Set([8, 17, 31, 42, 56, 73, 91]);
        const isReject = rejectIndices.has(i);
        const isLowerGrade = !isReject && (i % 5 === 0 && i <= 85);
        return {
          id: `det-125-${i}`,
          inspectionId: 'insp-125',
          onionIndex: i,
          detectionIndex: i,
          class: isReject ? 'REJECT' : isLowerGrade ? 'LOWER_GRADE' : 'ACCEPTABLE',
          category: isReject ? 'REJECT' : isLowerGrade ? 'LOWER_GRADE' : 'ACCEPTABLE',
          defect: isReject ? (i === 17 ? 'VISIBLE_ROT' : i === 31 ? 'SPROUTING' : 'BRUISING') : isLowerGrade ? 'SURFACE_DAMAGE' : 'NONE',
          defectType: isReject ? (i === 17 ? 'VISIBLE_ROT' : i === 31 ? 'SPROUTING' : 'BRUISING') : isLowerGrade ? 'SURFACE_DAMAGE' : 'NONE',
          confidence: 0.94,
          bboxX: (i % 10) * 9.2 + 4,
          bboxY: Math.floor((i - 1) / 10) * 9.2 + 4,
          bboxWidth: 7.5,
          bboxHeight: 7.5,
          size: 'Medium (55-65mm)',
          color: 'Red/Purple Scale',
          severity: isReject ? 'HIGH' : isLowerGrade ? 'LOW' : 'NONE',
          status: 'DETECTED',
          removed: false,
          createdAt: new Date().toISOString(),
        };
      }),
    },
  ],
  environmentalReadings: [
    { id: 'env-1', batchId: 'ON-2026-00125', temperature: 21.0, humidity: 64.0, source: 'ESP32_TELEMETRY', timestamp: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString() },
    { id: 'env-2', batchId: 'ON-2026-00125', temperature: 22.5, humidity: 68.0, source: 'ESP32_TELEMETRY', timestamp: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString() },
    { id: 'env-3', batchId: 'ON-2026-00125', temperature: 24.8, humidity: 76.5, source: 'ESP32_TELEMETRY', timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
    { id: 'env-4', batchId: 'ON-2026-00125', temperature: 26.5, humidity: 82.0, source: 'ESP32_TELEMETRY', timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString() },
  ],
  riskAssessments: [
    { id: 'risk-1', batchId: 'ON-2026-00125', riskScore: 28.0, riskLevel: 'LOW', humidityFactor: 15, temperatureFactor: 10, deteriorationFactor: 10, durationFactor: 20, initialQualityFactor: 15, potentialValueAtRisk: 2500, explanation: 'Initial storage within acceptable bounds.', timestamp: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString() },
    { id: 'risk-2', batchId: 'ON-2026-00125', riskScore: 45.0, riskLevel: 'MEDIUM', humidityFactor: 40, temperatureFactor: 25, deteriorationFactor: 20, durationFactor: 35, initialQualityFactor: 15, potentialValueAtRisk: 5500, explanation: 'Humidity rising in Bay B.', timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString() },
    { id: 'risk-3', batchId: 'ON-2026-00125', riskScore: 63.0, riskLevel: 'HIGH', humidityFactor: 75, temperatureFactor: 55, deteriorationFactor: 45, durationFactor: 50, initialQualityFactor: 15, potentialValueAtRisk: 9200, explanation: 'High humidity exposure accelerating rot probability.', timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString() },
    { id: 'risk-4', batchId: 'ON-2026-00125', riskScore: 78.0, riskLevel: 'HIGH', humidityFactor: 90, temperatureFactor: 70, deteriorationFactor: 65, durationFactor: 60, initialQualityFactor: 15, potentialValueAtRisk: 12000, explanation: 'Visible deterioration has increased while batch experienced prolonged high humidity (82% RH).', timestamp: new Date().toISOString() },
  ],
  recommendations: [
    {
      id: 'rec-125',
      batchId: 'ON-2026-00125',
      action: 'PRIORITIZE_DISPATCH',
      title: 'PRIORITIZE DISPATCH IMMEDIATELY',
      rationale: 'Visible deterioration has increased while the batch has experienced prolonged high humidity (82.0% RH) and elevated temperature (26.5°C). Dispatch now to minimize value loss.',
      reason: 'Visible rot trend detected in elevated ambient humidity.',
      status: 'PENDING',
      generatedAt: new Date().toISOString(),
      timestamp: new Date().toISOString(),
    },
  ],
  interventions: [],
  outcomes: null,
  devices: [
    {
      id: 'ESP32-WH-01',
      name: 'Onion Storage Sensor Node #1',
      apiKey: 'agri_esp32_secret_key_88921',
      deviceType: 'ESP32_ENVIRONMENTAL_NODE',
      status: 'ONLINE',
      lastSeen: new Date().toISOString(),
    },
  ],
  auditLogs: [
    { id: 'log-1', action: 'BATCH_CREATED', details: 'Batch ON-2026-00125 registered (500 kg)', timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString() },
    { id: 'log-2', action: 'SAMPLE_RECORDED', details: 'Representative sampling recorded from 5 locations (100 onions)', timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString() },
    { id: 'log-3', action: 'AI_INSPECTION_COMPLETED', details: 'AI camera inspection analyzed 100 onions: 76 Acceptable, 17 Lower Grade, 7 Reject. Assigned Grade B (Quality Score: 78/100)', timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString() },
    { id: 'log-4', action: 'RISK_ALERT_TRIGGERED', details: 'High risk alert generated (78/100) due to elevated humidity exposure (82% RH)', timestamp: new Date().toISOString() },
  ],
};

export const MOCK_BATCHES_LIST = [
  MOCK_DEMO_BATCH_125,
  { id: 'ON-2026-00121', batchCode: 'ON-2026-00121', crop: 'ONION', variety: 'Agrifound Dark Red', quantityKg: 1200, estimatedUnitValue: 110, totalBatchValue: 132000, sourceLocation: 'Pune Agricultural Zone', status: 'IN_STORAGE', initialGrade: 'A', currentGrade: 'A', qualityScore: 92, currentRiskScore: 14, currentRiskLevel: 'LOW', potentialValueAtRisk: 3500, registrationDate: new Date().toISOString() },
  { id: 'ON-2026-00122', batchCode: 'ON-2026-00122', crop: 'ONION', variety: 'Agrifound Dark Red', quantityKg: 850, estimatedUnitValue: 95, totalBatchValue: 80750, sourceLocation: 'Pune Agricultural Zone', status: 'IN_STORAGE', initialGrade: 'B', currentGrade: 'B', qualityScore: 81, currentRiskScore: 42, currentRiskLevel: 'MEDIUM', potentialValueAtRisk: 7200, registrationDate: new Date().toISOString() },
  { id: 'ON-2026-00123', batchCode: 'ON-2026-00123', crop: 'ONION', variety: 'Nashik Red Globe', quantityKg: 600, estimatedUnitValue: 80, totalBatchValue: 48000, sourceLocation: 'Lasalgaon Mandi', status: 'IN_STORAGE', initialGrade: 'C', currentGrade: 'C', qualityScore: 64, currentRiskScore: 71, currentRiskLevel: 'HIGH', potentialValueAtRisk: 11500, registrationDate: new Date().toISOString() },
  { id: 'ON-2026-00124', batchCode: 'ON-2026-00124', crop: 'ONION', variety: 'Nashik Red Globe', quantityKg: 950, estimatedUnitValue: 90, totalBatchValue: 85500, sourceLocation: 'Lasalgaon Mandi', status: 'IN_STORAGE', initialGrade: 'B', currentGrade: 'B', qualityScore: 76, currentRiskScore: 86, currentRiskLevel: 'CRITICAL', potentialValueAtRisk: 22000, registrationDate: new Date().toISOString() },
  { id: 'ON-2026-00126', batchCode: 'ON-2026-00126', crop: 'ONION', variety: 'Agrifound Dark Red', quantityKg: 1500, estimatedUnitValue: 115, totalBatchValue: 172500, sourceLocation: 'Pune Agricultural Zone', status: 'IN_STORAGE', initialGrade: 'A', currentGrade: 'A', qualityScore: 95, currentRiskScore: 12, currentRiskLevel: 'LOW', potentialValueAtRisk: 4000, registrationDate: new Date().toISOString() },
  { id: 'ON-2026-00127', batchCode: 'ON-2026-00127', crop: 'ONION', variety: 'Nashik Red Globe', quantityKg: 700, estimatedUnitValue: 95, totalBatchValue: 66500, sourceLocation: 'Lasalgaon Mandi', status: 'IN_STORAGE', initialGrade: 'B', currentGrade: 'B', qualityScore: 79, currentRiskScore: 48, currentRiskLevel: 'MEDIUM', potentialValueAtRisk: 6800, registrationDate: new Date().toISOString() },
  { id: 'ON-2026-00128', batchCode: 'ON-2026-00128', crop: 'ONION', variety: 'Nashik Red Globe', quantityKg: 450, estimatedUnitValue: 75, totalBatchValue: 33750, sourceLocation: 'Lasalgaon Mandi', status: 'IN_STORAGE', initialGrade: 'C', currentGrade: 'C', qualityScore: 61, currentRiskScore: 68, currentRiskLevel: 'HIGH', potentialValueAtRisk: 8900, registrationDate: new Date().toISOString() },
];
